"""empty message

Revision ID: fa91b8f577ee
Revises: 98b9d42a9999
Create Date: 2023-02-07 01:39:59.676371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa91b8f577ee'
down_revision = '98b9d42a9999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
